export const GET_SPACE_REQUEST = 'GET_SPACE_REQUEST'
export const GET_SPACE_SUCCESS = 'GET_SPACE_SUCCESS'
export const GET_SPACE_FAILED = 'GET_SPACE_FAILED'

export const ADD_SPACE_REQUEST = 'ADD_SPACE_REQUEST'
export const ADD_SPACE_SUCCESS = 'ADD_SPACE_SUCCESS'
export const ADD_SPACE_FAILED = 'ADD_SPACE_FAILED'

export const GETONE_SPACE_REQUEST = 'GETONE_SPACE_REQUEST'
export const GETONE_SPACE_SUCCESS = 'GETONE_SPACE_SUCCESS'
export const GETONE_SPACE_FAILED = 'GETONE_SPACE_FAILED'

export const GET_ANSWER_REQUEST = 'GET_ANSWER_REQUEST'
export const GET_ANSWER_SUCCESS = 'GET_ANSWER_SUCCESS'
export const GET_ANSWER_FAILED = 'GET_ANSWER_FAILED'

export const ADD_ANSWER_REQUEST = 'ADD_ANSWER_REQUEST'
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS'
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED'

export const GETONE_ANSWER_REQUEST = 'GETONE_ANSWER_REQUEST'
export const GETONE_ANSWER_SUCCESS = 'GETONE_ANSWER_SUCCESS'
export const GETONE_ANSWER_FAILED = 'GETONE_ANSWER_FAILED'


